name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

env:
  GH_TOKEN: ${{ github.token }}
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - uses: mkroening/rust-toolchain-toml@main
      - run: |
          rustup component add clippy llvm-tools
      - name: Clippy
        run: |
          cargo clippy --target x86_64-unknown-none

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: mkroening/rust-toolchain-toml@main
      - run: rustup component add rustfmt
      - name: Format
        run: cargo fmt -- --check

  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable
    - run: echo "$CARGO_HOME/bin" >> "$GITHUB_PATH"
    - uses: mkroening/rust-toolchain-toml@main
    - name: Show CPU features
      run: lscpu
    - name: Checkout kernel
      run: |
        cd ..
        git clone https://github.com/hermit-os/kernel.git
        cd kernel
        git checkout rhyve
        cd /home/runner/work/rhyve
    - name: Build dev profile
      run: cargo build
    - name: Build release profile
      run: cargo build --release
